function [aero_tables] = generate_aerotables(rocket_parameters, aerotable_parameters, options)
%GENERATE_AEROTABLES Create aerodynamic database from rocket parameters and put in model_inputs
%   Wraps creating aerodynamic database and transfering aerodynamic 
% database to struct to input into model.
arguments
    rocket_parameters
    aerotable_parameters
    options.target_batch_size double {mustBeInRange(options.target_batch_size, 1, 263)} = 263
    options.thread_number = 1
end

aero_tables = struct();
% Create table axes
aero_tables.ALT_axis1 = linspace(0, aerotable_parameters.ALT_max, ...
                                  aerotable_parameters.ALT_iterations);
aero_tables.PHI_axis2 = linspace(-180, 180, ...
                                  aerotable_parameters.PHI_iterations);
aero_tables.ALPHA_axis3 = aerotable_parameters.ALPHA;
aero_tables.MACH_axis4 = aerotable_parameters.MACH;

% Generate Aerodynamic Database
if options.thread_number == 1
    aerotable = Generate_Aero_Database( ...
        aero_tables.ALT_axis1, ... % Table Axes
        aero_tables.PHI_axis2, ...
        aero_tables.ALPHA_axis3, ...
        aero_tables.MACH_axis4, ...
        rocket_parameters.SREF, ... % General
        rocket_parameters.LREF, ...
        rocket_parameters.COM_table(end, 2), ...
        rocket_parameters.NC_type, ... % Nosecone
        rocket_parameters.NC_power, ...
        rocket_parameters.NC_length, ...
        rocket_parameters.NC_diam, ...
        rocket_parameters.AF1_length, ... % Airframe
        rocket_parameters.AF1_diam, ...
        rocket_parameters.FN1_number, ... % Fins
        rocket_parameters.FN1_type, ...
        rocket_parameters.FN1_NACA, ...
        rocket_parameters.FN1_height, ...
        rocket_parameters.FN1_root, ...
        rocket_parameters.FN1_tip, ...
        rocket_parameters.FN1_XLE, ...
        rocket_parameters.FN1_sweep, ...
        rocket_parameters.FN1_edgeRad, ...
        rocket_parameters.ZUPPER, ... % Fin Cross-section
        rocket_parameters.ZLOWER, ...
        rocket_parameters.LMAXU, ...
        rocket_parameters.LMAXL, ...
        rocket_parameters.LFLATU, ...
        rocket_parameters.LFLATL, ... 
        rocket_parameters.ROUGH, ...
        rocket_parameters.DEXIT, ...
        options.target_batch_size);
else
    aerotable = Schedule_Aero_Database_Jobs( ...
        aero_tables.ALT_axis1, ... % Table Axes
        aero_tables.PHI_axis2, ...
        aero_tables.ALPHA_axis3, ...
        aero_tables.MACH_axis4, ...
        rocket_parameters.SREF, ... % General
        rocket_parameters.LREF, ...
        rocket_parameters.COM_table(end, 2), ...
        rocket_parameters.NC_type, ... % Nosecone
        rocket_parameters.NC_power, ...
        rocket_parameters.NC_length, ...
        rocket_parameters.NC_diam, ...
        rocket_parameters.AF1_length, ... % Airframe
        rocket_parameters.AF1_diam, ...
        rocket_parameters.FN1_number, ... % Fins
        rocket_parameters.FN1_type, ...
        rocket_parameters.FN1_NACA, ...
        rocket_parameters.FN1_height, ...
        rocket_parameters.FN1_root, ...
        rocket_parameters.FN1_tip, ...
        rocket_parameters.FN1_XLE, ...
        rocket_parameters.FN1_sweep, ...
        rocket_parameters.FN1_edgeRad, ...
        rocket_parameters.ZUPPER, ... % Fin Cross-section
        rocket_parameters.ZLOWER, ...
        rocket_parameters.LMAXU, ...
        rocket_parameters.LMAXL, ...
        rocket_parameters.LFLATU, ...
        rocket_parameters.LFLATL, ...
        rocket_parameters.ROUGH, ...
        rocket_parameters.DEXIT, ...
        options.target_batch_size, ...
        options.thread_number);
end

%% Save Necessary Variables to Model Input Struct
aero_tables.CA_sustainer = aerotable.CA_sustainer;
aero_tables.CY_sustainer = aerotable.CY_sustainer;
aero_tables.CN_sustainer = aerotable.CN_sustainer;
aero_tables.CLL_sustainer = aerotable.CLL_sustainer;
aero_tables.CM_sustainer = aerotable.CM_sustainer;
aero_tables.CLN_sustainer = aerotable.CLN_sustainer;
aero_tables.CMQ_sustainer = aerotable.CMQ_sustainer;
aero_tables.CMAD_sustainer = aerotable.CMAD_sustainer; 
aero_tables.CLP_sustainer = aerotable.CLP_sustainer;
aero_tables.CLR_sustainer = aerotable.CLR_sustainer;
aero_tables.CNP_sustainer = aerotable.CNP_sustainer;
aero_tables.CNR_sustainer = aerotable.CNR_sustainer;
aero_tables.CAQ_sustainer = aerotable.CAQ_sustainer;
aero_tables.CNQ_sustainer = aerotable.CNQ_sustainer;
aero_tables.CNAD_sustainer = aerotable.CNAD_sustainer; 
aero_tables.CYR_sustainer = aerotable.CYR_sustainer;
aero_tables.CYP_sustainer = aerotable.CYP_sustainer;
aero_tables.CLB_sustainer = aerotable.CLB_sustainer;
aero_tables.CYB_sustainer = aerotable.CYB_sustainer;
aero_tables.CNB_sustainer = aerotable.CNB_sustainer;
aero_tables.XCP_sustainer = aerotable.XCP_sustainer;
aero_tables.CD_sustainer = aerotable.CD_sustainer;
aero_tables.CL_sustainer = aerotable.CL_sustainer;

end

